version: '3.8'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    networks:
      front-network:

  redis:
      image: 'redis:alpine'
      restart: always
      expose:
        - '6379'

  wordpress:
    image: docker.io/bitnami/wordpress:latest
    expose:
      - '8080'
      - '8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - './wp-config.php:/bitnami/wordpress/wp-config.php'
    depends_on:
      - mariadb
      - redis
    deploy:
      replicas: 2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      #- WORDPRESS_USER=user
      #- WORDPRESS_PASSWORD=bitnami
    networks:
      front-network:

  proxy:
    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    
    ports:
      - 80:80
    depends_on: 
      - wordpress
    networks:
      - front-network

networks:
  # Un network nommé front-network qui utilise le driver bridge
  front-network:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data: